version: '3'
services:
  botstrap_server:
    tty: true
    build: ./botstrap_server
    ports:
      - "8080:8080"
    volumes:
      - ./botstrap_server:/usr/src/app/botstrap_server
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8080